### ISSUE TITLE
create a navbar component

### ISSUE THREAD

**Issue by sumeet-bansal** [sumeet-bansal/sedsucsd.org#1]
1. rename `assets/blocks/nav_bar.php` to `.../navbar.php`
2. rename `index.html` to `index.php` and replace the navbar in that page with the [PHP partial](https://www.w3schools.com/php/php_includes.asp)
3. update the PHP partial to match the current navbar

**Comment by rainarit** [comment]
One question, for the second part, how can I find the navbar in index.php, do you mean the navigation panel? Also, should I put in the `include` statement like `<?php include 'navbar.php';?>`

**Comment by sumeet-bansal** [comment]
Yup! The navbar is in the HTML and we need to replace that snippet of HTML with the PHP include so that there aren’t multiple copies of the same code floating around; using the PHP include instead of maintaining separate copies of the same HTML on each page makes it significantly easier to make changes to the navbar across the entire site since we only have to edit it once (in the PHP block) instead of on every page.

**Comment by rainarit** [comment]
Just wanted to make sure. I replaced the HTML code from the Navigation Panel to `<?php include 'navbar.php';?>`. Should I do this to other HTML files?
